#!/usr/bin/bash

echo
echo "> Downloading template vpc"
curl -so vpc https://raw.githubusercontent.com/peterhodes/aws-cloudformation/main/vpc
echo "> Creating stack-vpc"
aws cloudformation create-stack --stack-name stack-vpc --template-body file://vpc



echo
echo "> Fetching VpcId"
CreateComplete=$(aws cloudformation list-stacks --stack-status-filter CREATE_COMPLETE --query 'StackSummaries[?StackName==`stack-vpc`]' --output text)
while [ "$CreateComplete" == "" ]
do
    echo  `date +"%H:%M:%S   waiting for  stack-vpc  creation to complete"`
    sleep 5
    CreateComplete=$(aws cloudformation list-stacks --stack-status-filter CREATE_COMPLETE --query 'StackSummaries[?StackName==`stack-vpc`]' --output text)
done
VpcId=$(aws cloudformation list-stack-resources --stack-name stack-vpc --query 'StackResourceSummaries[*].PhysicalResourceId')
echo "> Vpc Id is  >$VpcId<"



echo
echo "> Downloading template subnet"
curl -so subnet https://raw.githubusercontent.com/peterhodes/aws-cloudformation/main/subnet
echo "> Creating stack-subnet"
aws cloudformation create-stack --stack-name stack-subnet --template-body file://subnet --parameters ParameterKey=paramVpcId,ParameterValue=$VpcId



echo
echo "> Fetching SubnetId"
CreateComplete=$(aws cloudformation list-stacks --stack-status-filter CREATE_COMPLETE --query 'StackSummaries[?StackName==`stack-subnet`]' --output text)                 
while [ "$CreateComplete" == "" ]
do
    echo  `date +"%H:%M:%S   waiting for  stack-subnet  creation to complete"`
    sleep 5
    CreateComplete=$(aws cloudformation list-stacks --stack-status-filter CREATE_COMPLETE --query 'StackSummaries[?StackName==`stack-subnet`]' --output text)
done
SubnetId=$(aws cloudformation list-stack-resources --stack-name stack-subnet --query 'StackResourceSummaries[*].PhysicalResourceId')
echo "> Subnet Id is  >$SubnetId<"



echo
echo "> Downloading template routetable"
curl -so routetable https://raw.githubusercontent.com/peterhodes/aws-cloudformation/main/routetable
echo "> Creating stack-routetable"
aws cloudformation create-stack --stack-name stack-routetable --template-body file://routetable --parameters ParameterKey=paramVpcId,ParameterValue=$VpcId



echo
echo "> Downloading template securitygroup"
curl -so securitygroup https://raw.githubusercontent.com/peterhodes/aws-cloudformation/main/securitygroup
echo "> Creating stack-securitygroup"
aws cloudformation create-stack --stack-name stack-securitygroup --template-body file://securitygroup --parameters ParameterKey=paramVpcId,ParameterValue=$VpcId



echo
echo "> Downloading template internetgateway"
curl -so internetgateway https://raw.githubusercontent.com/peterhodes/aws-cloudformation/main/internetgateway
echo "> Creating stack-internetgateway"
aws cloudformation create-stack --stack-name stack-internetgateway --template-body file://internetgateway



echo
echo "> Fetching IgwId"
CreateComplete=$(aws cloudformation list-stacks --stack-status-filter CREATE_COMPLETE --query 'StackSummaries[?StackName==`stack-internetgateway`]' --output text)
while [ "$CreateComplete" == "" ]
do
    echo  `date +"%H:%M:%S   waiting for  stack-internetgateway  creation to complete"`
    sleep 5
    CreateComplete=$(aws cloudformation list-stacks --stack-status-filter CREATE_COMPLETE --query 'StackSummaries[?StackName==`stack-internetgateway`]' --output text)
done
IgwId=$(aws cloudformation list-stack-resources --stack-name stack-internetgateway --query 'StackResourceSummaries[*].PhysicalResourceId')
echo "> Igw Id is  >$IgwId<"



echo
echo "> Downloading template vpcgatewayattachment"
curl -so vpcgatewayattachment https://raw.githubusercontent.com/peterhodes/aws-cloudformation/main/vpcgatewayattachment
echo "> Creating stack-vpcgatewayattachment"
aws cloudformation create-stack --stack-name stack-vpcgatewayattachment --template-body file://vpcgatewayattachment --parameters ParameterKey=paramVpcId,ParameterValue=$VpcId ParameterKey=paramIgwId,ParameterValue=$IgwId



echo
echo "> Fetching RouteTableId"
CreateComplete=$(aws cloudformation list-stacks --stack-status-filter CREATE_COMPLETE --query 'StackSummaries[?StackName==`stack-routetable`]' --output text)
while [ "$CreateComplete" == "" ]
do
    echo  `date +"%H:%M:%S   waiting for  stack-routetable  creation to complete"`
    sleep 5
    CreateComplete=$(aws cloudformation list-stacks --stack-status-filter CREATE_COMPLETE --query 'StackSummaries[?StackName==`stack-routetable`]' --output text)
done
RouteTableId=$(aws cloudformation list-stack-resources --stack-name stack-routetable --query 'StackResourceSummaries[*].PhysicalResourceId')
echo "> RouteTable Id is  >$RouteTableId<"



echo
echo "> Downloading template route"
curl -so route https://raw.githubusercontent.com/peterhodes/aws-cloudformation/main/route
echo "> Creating stack-route"
aws cloudformation create-stack --stack-name stack-route --template-body file://route --parameters ParameterKey=paramRouteTableId,ParameterValue=$RouteTableId ParameterKey=paramGatewayId,ParameterValue=$IgwId



echo
echo "> Downloading template subnetroutetableassociation"
curl -so subnetroutetableassociation https://raw.githubusercontent.com/peterhodes/aws-cloudformation/main/subnetroutetableassociation
echo "> Creating stack-subnetroutetableassociation"
aws cloudformation create-stack --stack-name stack-subnetroutetableassociation --template-body file://subnetroutetableassociation --parameters ParameterKey=paramSubnetId,ParameterValue=$SubnetId ParameterKey=paramRouteTableId,ParameterValue=$RouteTableId



echo
echo "> Fetching SecurityGroupId"
CreateComplete=$(aws cloudformation list-stacks --stack-status-filter CREATE_COMPLETE --query 'StackSummaries[?StackName==`stack-securitygroup`]' --output text)
while [ "$CreateComplete" == "" ]
do
    echo  `date +"%H:%M:%S   waiting for  stack-securitygroup  creation to complete"`
    sleep 5
    CreateComplete=$(aws cloudformation list-stacks --stack-status-filter CREATE_COMPLETE --query 'StackSummaries[?StackName==`stack-securitygroup`]' --output text)
done
SecurityGroupId=$(aws cloudformation list-stack-resources --stack-name stack-securitygroup --query 'StackResourceSummaries[*].PhysicalResourceId')
echo "> SecurityGroup Id is  >$SecurityGroupId<"





echo
echo "> Downloading template ec2instance"
curl -so ec2instance https://raw.githubusercontent.com/peterhodes/aws-cloudformation/main/ec2instance
echo "> Creating stack-ec2instance"
aws cloudformation create-stack --stack-name stack-ec2instance     --template-body file://ec2instance --parameters ParameterKey=paramSubnetId,ParameterValue=$SubnetId ParameterKey=paramKeyPair,ParameterValue=peterKeyPair ParameterKey=paramSecurityGroupIds,ParameterValue=peterKeyPair
echo "> Creating stack-ec2instance-def"
aws cloudformation create-stack --stack-name stack-ec2instance-def --template-body file://ec2instance --parameters ParameterKey=paramSubnetId,ParameterValue=subnet-014e7113747bddfe9 ParameterKey=paramKeyPair,ParameterValue=peterKeyPair



