#!/usr/bin/bash


# This demo creates two stacks - first a stack for a VPC and then a second stack for a SUBNET.
# At first glance this might seem a bit odd as we could create them in a single stack and remove some complexity around getting the VPC ID.
# I think that small amount of complexity is added in a way that adds some valuable content and necessitates the introduction of parameters in a way that is relatively simple.

# I've added comments so that what is happening can be seen.
# It will be necessary to have access to the AWS CLI.

# I would suggest after running the demo - to run each of the aws cli commands below - to build a picture of the resources you've created and how they relate to the stacks.


echo "> Downloading vpc"
curl -so vpc https://raw.githubusercontent.com/peterhodes/aws-cloudformation/main/vpc
echo "> Creating stack-vpc"
aws cloudformation create-stack --stack-name stack-vpc --template-body file://vpc

CreateComplete=""
while [ "$CreateComplete" == "" ]
do
    echo  `date +"%m-%d %H:%M:%S   not proceeding until stack creation completes"`
    sleep 5
    CreateComplete=$(aws cloudformation list-stacks --stack-status-filter CREATE_COMPLETE --query 'StackSummaries[?StackName==`stack-vpc`]' --output text)
done
VpcId=$(aws cloudformation list-stack-resources --stack-name stack-vpc --query 'StackResourceSummaries[*].PhysicalResourceId')
echo ">Vpc Id is  >$VpcId<"     # We need to know the VPC ID to let the subnet know which VPC its going to become a member of.



echo ">Downloading subnet"
curl -so subnet https://raw.githubusercontent.com/peterhodes/aws-cloudformation/main/subnet
echo "> Creating stack-subnet"
aws cloudformation create-stack --stack-name stack-subnet --template-body file://subnet --parameters ParameterKey=paramVpcId,ParameterValue=$VpcId
